- id: cog
  name: cog (regenerate files)
  description: Find files with cog markers and run cog on them
  entry: pre-commit-cog
  language: python
  language_version: python3.12
  pass_filenames: false
  always_run: true
- id: init-hooks
  name: init-hooks (ensure baseline hooks)
  description: Ensures that a baseline set of pre-commit hooks are enabled in the repository
  entry: pre-commit-init-hooks
  language: python
  language_version: python3.12
  pass_filenames: false
  always_run: true
- id: uv-run
  name: uv-run (execute command with uv)
  description: Executes a project command using uv run
  entry: pre-commit-uv-run
  language: python
  language_version: python3.12
  pass_filenames: false
  always_run: true
