# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
- pre-commit
- pre-push
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: ^\.idea
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-toml
  - id: check-xml
  - id: check-added-large-files
  - id: forbid-submodules
  - id: mixed-line-ending
- repo: https://github.com/google/yamlfmt
  rev: v0.17.2
  hooks:
  - id: yamlfmt
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 3.2.1
  hooks:
  - id: editorconfig-checker
    exclude: LICENSE|^\.idea
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.2
  hooks:
  - id: check-github-workflows
  - id: check-renovate
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 41.21.1
  hooks:
  - id: renovate-config-validator
    args: [--strict]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.2
  hooks:
  - id: ruff-format
  - id: ruff-check
    args:
    - --fix
    - --unsafe-fixes
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.19
  hooks:
  - id: uv-lock
- repo: https://github.com/andrewaylett/pre-commit-hooks
  rev: v0.2.0
  hooks:
  - id: cog
- repo: local
  hooks:
  - id: test
    name: Run Pytest
    language: python
    entry: uv run pytest
    additional_dependencies:
    - "uv==0.7.19"
    pass_filenames: false
    always_run: true
