"""Test file with cog markers for testing the cog pre-commit hook."""


def example_function():
    """Example function with cog-generated content."""
    # [[[cog
    # import cog
    # cog.outl("    print('This content was generated by cog!')")
    # ]]]
    print("This content was generated by cog!")
    # [[[end]]] (sum: TXTjvmD4z2)

    return "Hello, world!"


def test_example_function():
    """Test that the example function returns the expected value."""
    result = example_function()
    assert result == "Hello, world!"


def test_cog_content():
    """Test that the cog-generated content is present in the file."""
    # This test is a bit artificial, but it demonstrates how to test cog-generated content
    with open(__file__) as f:
        content = f.read()
    assert "print('This content was generated by cog!')" in content
