"""Test file with cog markers for testing the cog pre-commit hook."""


def example_function():
    """Example function with cog-generated content."""
    # [[[cog
    # import cog
    # cog.outl("    print('This content was generated by cog!')")
    # ]]]
    print("This content was generated by cog!")
    # [[[end]]] (sum: TXTjvmD4z2)

    return "Hello, world!"
