name: Validate
on:
  push:
    branches: ["main", "renovate/*"]
  pull_request:
permissions:
  contents: read
  checks: write
  packages: write
jobs:
  test:
    name: Pre-Commit and Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - uses: andrewaylett/pre-commit-action@7ec43925409e698357437cff4e84ee03fc72f668 # v4
